-- ============================================================
-- DROP TABLES IN CORRECT ORDER (considering foreign keys)
-- ============================================================
DROP VIEW IF EXISTS vw_locked_sap_users;
DROP VIEW IF EXISTS vw_active_sap_users;
DROP TABLE IF EXISTS user_address;
DROP TABLE IF EXISTS sap_info;
DROP TABLE IF EXISTS COMPANY_ADDRESS;
DROP TABLE IF EXISTS COMPANY_INFO;
DROP TABLE IF EXISTS jwt_blacklist;
DROP TABLE IF EXISTS bu_info;
DROP TABLE IF EXISTS admin_login_info;

-- Role Management tables (dropped in correct order)
DROP TABLE IF EXISTS PORTAL_USER_ROLE;
DROP TABLE IF EXISTS ROLE_RESOURCE;
DROP TABLE IF EXISTS RESOURCE;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS COUNTRY;

-- ============================================================
-- CREATE TABLES
-- ============================================================

-- Create admin_login_info table WITH RESET TOKEN COLUMNS
CREATE TABLE admin_login_info (
    admin_id VARCHAR(50) PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20),
    department VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reset_token VARCHAR(255),
    token_expiry TIMESTAMP
);

CREATE TABLE bu_info (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    friendly_name VARCHAR(255),
    layer INT,
    parent_id BIGINT DEFAULT 0,
    delete_status VARCHAR(1) DEFAULT '0',
    created_by VARCHAR(50),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(50),
    modification_time TIMESTAMP,
    sale_organize_id BIGINT,
    bu_admin_id BIGINT,
    admin_id VARCHAR(50) NOT NULL
    -- Add country_code if needed
    -- country_code VARCHAR(10)
);

-- Now you can add columns if needed (but they're already in CREATE TABLE)
-- ALTER TABLE bu_info ADD COLUMN IF NOT EXISTS country_code VARCHAR(10);
CREATE TABLE IF NOT EXISTS sale_organize (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sale_organize_id VARCHAR(50) NOT NULL,
    sale_organize_short VARCHAR(10),
    sale_organize_name VARCHAR(200),
    channel VARCHAR(50),
    admin_id VARCHAR(50),
    delete_status VARCHAR(1) DEFAULT '0',
    created_by VARCHAR(50),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Create jwt_blacklist table
CREATE TABLE jwt_blacklist (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(500) NOT NULL UNIQUE,
    blacklisted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create COUNTRY table
CREATE TABLE COUNTRY (
    ID BIGINT PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100),
    BU_ID BIGINT,
    SUB_BU_ID BIGINT
);

-- Create ROLE table with H2-compatible syntax
CREATE TABLE ROLE (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BU_ID BIGINT NOT NULL,
    ROLE_NAME VARCHAR(64) NOT NULL,
    DELETE_STATUS CHAR(1) NOT NULL DEFAULT '0',
    IS_DEFAULT CHAR(1) NOT NULL DEFAULT '0',
    CREATED_BY VARCHAR(50),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFICATION_TIME TIMESTAMP,
    TYPE INT,
    PAGE_PERMISSION CLOB,
    SUB_BU_ID BIGINT,
    COUNTRY_ID BIGINT,
    DESCRIPTION VARCHAR(1000)
);

-- Create RESOURCE table
CREATE TABLE RESOURCE (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    TYPE CHAR(1) NOT NULL,
    AUTHORITY_ATTR VARCHAR(64),
    URL VARCHAR(255),
    PARENT_ID BIGINT NOT NULL DEFAULT 0,
    CREATED_BY VARCHAR(50),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFICATION_TIME TIMESTAMP,
    DELETE_STATUS CHAR(1) NOT NULL DEFAULT '0',
    IS_DEFAULT CHAR(1) NOT NULL DEFAULT '0',
    CODE VARCHAR(128),
    SORT INT
);

-- Create ROLE_RESOURCE table
CREATE TABLE ROLE_RESOURCE (
    ROLE_ID BIGINT NOT NULL,
    RESOURCE_ID BIGINT NOT NULL,
    PRIMARY KEY (ROLE_ID, RESOURCE_ID)
);

-- Create PORTAL_USER_ROLE table
CREATE TABLE PORTAL_USER_ROLE (
    USER_ID VARCHAR NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

-- Create COMPANY_INFO table with VARCHAR columns
CREATE TABLE COMPANY_INFO (
    ID BIGINT PRIMARY KEY,
    BU_ID BIGINT NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    COMPANY_NAME VARCHAR(800) NOT NULL,
    DELETE_STATUS VARCHAR(10) DEFAULT 'ACTIVE',
    IS_ACTIVE VARCHAR(10) DEFAULT 'YES',
    CREATED_BY VARCHAR(50),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFICATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PROVINCE VARCHAR(128),
    PHONE VARCHAR(256),
    ADDRESS VARCHAR(1500),
    ADDRESS2 VARCHAR(1500),
    ZIPCODE VARCHAR(32),
    TAX_ID VARCHAR(32),
    VERTICAL_INDUSTRY_TYPE VARCHAR(64),
    STATUS VARCHAR(10),
    SAP_ID VARCHAR(50),
    LOCK_REASON VARCHAR(1000),
    EMAIL VARCHAR(256),
    LOCATION VARCHAR(10),
    MOUNTHLY_TURNOVER VARCHAR(10),
    PANNO_TYPE VARCHAR(10),
    PANNO VARCHAR(256),
    COMPANY_TYPE VARCHAR(10),
    ADDITION_BUSINESS_TYPE VARCHAR(10),
    SUB_BU_ID BIGINT,
    CITY VARCHAR(100),
    STATE_NOTE VARCHAR(100),
    CITY_NOTE VARCHAR(100),
    SALE_GROUP VARCHAR(50),
    USER_GROUP VARCHAR(50),
    USER_GRADE VARCHAR(50),
    USER_AREA VARCHAR(50),
    REGION_ID VARCHAR(50),
    DISTRICT VARCHAR(200),
    DISTRICT_ID VARCHAR(50),
    SALE_CHANNEL VARCHAR(10),
    HANA_SAP_ID VARCHAR(50),
    SPECIAL_SUPPORT_TIME_START INT,
    SPECIAL_SUPPORT_TIME_END INT,
    BRANCH_COMPANY VARCHAR(20),
    FORCE_KYC_POPUP INT,
    ACCOUNT_DEACTIVE VARCHAR(10) DEFAULT 'NO',
    ACCOUNT_DEACTIVE_INFO TEXT
);

-- Create COMPANY_ADDRESS table
CREATE TABLE COMPANY_ADDRESS (
    ADDRESS_ID BIGINT PRIMARY KEY,
    USER_SAP_ID VARCHAR(50),
    ADDRESS_COUNTRY_CODE VARCHAR(10),
    ADDRESS_PROVINCE VARCHAR(50),
    ADDRESS_CITY VARCHAR(100),
    ADDRESS_STREET VARCHAR(100),
    ADDRESS_ZIPCODE VARCHAR(10),
    ADDRESS_TYPE VARCHAR(50),
    SHIPTO_ID VARCHAR(50),
    DEFAULT_ADDRESS VARCHAR(50),
    ADDRESS VARCHAR(2000),
    ADDRESS_CONTACT VARCHAR(500),
    ADDRESS_EMAIL VARCHAR(1000),
    ADDRESS_TELPHONE VARCHAR(1000),
    ADDRESS_NAME VARCHAR(1000),
    ADDRESS_PROVINCE_CODE VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFICATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETE_STATUS VARCHAR(50) DEFAULT 'ACTIVE'
);

-- SAP Info table for H2 database
CREATE TABLE sap_info (
    user_id VARCHAR(50) PRIMARY KEY,
    user_sap_id VARCHAR(50) UNIQUE NOT NULL,
    is_lock VARCHAR(1) DEFAULT 'N',
    user_name VARCHAR(200),
    user_name_cipher VARCHAR(500),
    start_valid_date TIMESTAMP,
    end_valid_date TIMESTAMP,
    user_email VARCHAR(100),
    user_email_cipher VARCHAR(500),
    user_telphone VARCHAR(50),
    user_telphone_cipher VARCHAR(200),
    user_mobile VARCHAR(20),
    user_mobile_cipher VARCHAR(100),
    user_mobile_country_code VARCHAR(10),
    user_mobile_country_code_cipher VARCHAR(50),
    user_sale_sap_id VARCHAR(50),
    currency_code VARCHAR(10),
    language_code VARCHAR(10),
    user_sale_org VARCHAR(50),
    user_sale_dept VARCHAR(50),
    user_sale_group VARCHAR(50),
    user_country_code VARCHAR(10),
    user_password VARCHAR(255),
    user_salt VARCHAR(100),
    created_by VARCHAR(50),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(50),
    modification_time TIMESTAMP,
    delete_status VARCHAR(1) DEFAULT '0',
    password_modification_time TIMESTAMP,
    auth_law VARCHAR(100),
    user_parent_id VARCHAR(50),
    user_level VARCHAR(10),
    short_message VARCHAR(500),
    sap_user_group VARCHAR(50),
    is_reset_password VARCHAR(1),
    reset_password_time TIMESTAMP,
    user_grade VARCHAR(10),
    user_area VARCHAR(100),
    user_photo VARCHAR(500),
    region VARCHAR(100),
    region_id VARCHAR(50),
    pan_number VARCHAR(50),
    gst_number VARCHAR(100),
    sale_email VARCHAR(100),
    sale_email_cipher VARCHAR(500),
    sap_price_group VARCHAR(50),
    branch VARCHAR(100),
    user_address_lock VARCHAR(1),
    district VARCHAR(100),
    payment_term VARCHAR(100),
    district_id VARCHAR(50),
    payment_term_id VARCHAR(50),
    user_sale_name VARCHAR(200),
    branch_manager_sap_id VARCHAR(50),
    branch_manager_name VARCHAR(200),
    reginal_manager_sap_id VARCHAR(50),
    reginal_manager_name VARCHAR(200),
    user_stock_show VARCHAR(1),
    download_stock_list_show VARCHAR(1),
    add_coupons VARCHAR(1),
    show_coupons_windows VARCHAR(1),
    sale_channel VARCHAR(50),
    add_flash_sales VARCHAR(1),
    user_config TEXT,
    reset_device_password VARCHAR(1),
    user_sap_id1 VARCHAR(50),
    sale_organize_id VARCHAR(50),
    sales_name VARCHAR(200),
    country_name VARCHAR(100),
    user_group_name VARCHAR(100),
    reason VARCHAR(500),
    dt_row_id VARCHAR(100),
    finance_email VARCHAR(100),
    purchase_email VARCHAR(100),
    user_sap_ids TEXT,
    b2b_user VARCHAR(1),
    special_support_time_start TIMESTAMP,
    special_support_time_end TIMESTAMP,
    group_ids TEXT,
    customer_name VARCHAR(200),
    last_login_time TIMESTAMP
);

-- Create a table for user address
CREATE TABLE user_address (
    address_id VARCHAR(50) PRIMARY KEY,
    user_sap_id VARCHAR(50),
    address_type VARCHAR(20),
    address_line1 VARCHAR(200),
    address_line2 VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    is_default VARCHAR(1) DEFAULT 'N',
    created_by VARCHAR(50),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(50),
    modification_time TIMESTAMP,
    delete_status VARCHAR(1) DEFAULT '0'
);

-- ============================================================
-- CREATE INDEXES WITH 'IF NOT EXISTS' FOR H2 COMPATIBILITY
-- ============================================================

-- Indexes for admin_login_info
CREATE INDEX IF NOT EXISTS idx_admin_username ON admin_login_info(username);
CREATE INDEX IF NOT EXISTS idx_admin_email ON admin_login_info(email);

-- Indexes for bu_info
CREATE INDEX IF NOT EXISTS idx_bu_admin ON bu_info(admin_id);

-- Indexes for jwt_blacklist
CREATE INDEX IF NOT EXISTS idx_blacklist_token ON jwt_blacklist(token);

-- Indexes for COUNTRY
CREATE INDEX IF NOT EXISTS idx_country_bu ON COUNTRY(BU_ID);

-- Indexes for ROLE
CREATE INDEX IF NOT EXISTS idx_role_name ON ROLE(ROLE_NAME);
CREATE INDEX IF NOT EXISTS idx_role_country ON ROLE(COUNTRY_ID);
CREATE INDEX IF NOT EXISTS idx_role_type ON ROLE(TYPE);
CREATE INDEX IF NOT EXISTS idx_role_delete_status ON ROLE(DELETE_STATUS);

-- Indexes for RESOURCE
CREATE INDEX IF NOT EXISTS idx_resource_parent ON RESOURCE(PARENT_ID);
CREATE INDEX IF NOT EXISTS idx_resource_sort ON RESOURCE(SORT);
CREATE INDEX IF NOT EXISTS idx_resource_delete_status ON RESOURCE(DELETE_STATUS);

-- Indexes for COMPANY_INFO
CREATE INDEX IF NOT EXISTS IDX_COMPANY_NAME ON COMPANY_INFO(COMPANY_NAME);
CREATE INDEX IF NOT EXISTS IDX_SAP_ID ON COMPANY_INFO(SAP_ID);
CREATE INDEX IF NOT EXISTS IDX_DELETE_STATUS ON COMPANY_INFO(DELETE_STATUS);
CREATE INDEX IF NOT EXISTS IDX_IS_ACTIVE ON COMPANY_INFO(IS_ACTIVE);
CREATE INDEX IF NOT EXISTS idx_company_country ON COMPANY_INFO(COUNTRY_ID);
CREATE INDEX IF NOT EXISTS idx_company_bu ON COMPANY_INFO(BU_ID);

-- Indexes for COMPANY_ADDRESS (FIXED: REMOVED DUPLICATES)
CREATE INDEX IF NOT EXISTS IDX_USER_SAP_ID ON COMPANY_ADDRESS(USER_SAP_ID);
CREATE INDEX IF NOT EXISTS IDX_DEFAULT_ADDRESS ON COMPANY_ADDRESS(DEFAULT_ADDRESS);
CREATE INDEX IF NOT EXISTS IDX_DELETE_STATUS ON COMPANY_ADDRESS(DELETE_STATUS);

-- Indexes for sap_info
CREATE INDEX IF NOT EXISTS idx_user_sap_id ON sap_info(user_sap_id);
CREATE INDEX IF NOT EXISTS idx_user_email ON sap_info(user_email);
CREATE INDEX IF NOT EXISTS idx_user_mobile ON sap_info(user_mobile);
CREATE INDEX IF NOT EXISTS idx_pan_number ON sap_info(pan_number);
CREATE INDEX IF NOT EXISTS idx_gst_number ON sap_info(gst_number);
CREATE INDEX IF NOT EXISTS idx_delete_status ON sap_info(delete_status);
CREATE INDEX IF NOT EXISTS idx_is_lock ON sap_info(is_lock);
CREATE INDEX IF NOT EXISTS idx_region_id ON sap_info(region_id);
CREATE INDEX IF NOT EXISTS idx_district_id ON sap_info(district_id);
CREATE INDEX IF NOT EXISTS idx_sap_user_group ON sap_info(sap_user_group);
CREATE INDEX IF NOT EXISTS idx_creation_time ON sap_info(creation_time);
CREATE INDEX IF NOT EXISTS idx_user_sale_sap_id ON sap_info(user_sale_sap_id);
CREATE INDEX IF NOT EXISTS idx_user_parent_id ON sap_info(user_parent_id);
CREATE INDEX IF NOT EXISTS idx_branch_manager_sap_id ON sap_info(branch_manager_sap_id);
CREATE INDEX IF NOT EXISTS idx_reginal_manager_sap_id ON sap_info(reginal_manager_sap_id);

-- Indexes for user_address
CREATE INDEX IF NOT EXISTS idx_address_user_sap_id ON user_address(user_sap_id);
CREATE INDEX IF NOT EXISTS idx_address_type ON user_address(address_type);

-- Indexes for ROLE_RESOURCE
CREATE INDEX IF NOT EXISTS idx_role_resource_role ON ROLE_RESOURCE(ROLE_ID);
CREATE INDEX IF NOT EXISTS idx_role_resource_resource ON ROLE_RESOURCE(RESOURCE_ID);

-- Indexes for PORTAL_USER_ROLE
CREATE INDEX IF NOT EXISTS idx_portal_user_role_user ON PORTAL_USER_ROLE(USER_ID);
CREATE INDEX IF NOT EXISTS idx_portal_user_role_role ON PORTAL_USER_ROLE(ROLE_ID);

-- ============================================================
-- CREATE VIEWS WITH 'OR REPLACE' FOR H2 COMPATIBILITY
-- ============================================================

-- Create view for active users
CREATE OR REPLACE VIEW vw_active_sap_users AS
SELECT
    user_sap_id,
    user_name,
    user_email,
    user_mobile,
    user_level,
    sap_user_group,
    user_grade,
    region,
    district,
    user_sale_name,
    creation_time,
    last_login_time,
    is_lock,
    start_valid_date,
    end_valid_date
FROM sap_info
WHERE delete_status = '0'
  AND (end_valid_date IS NULL OR end_valid_date > CURRENT_TIMESTAMP);

-- Create view for locked users
CREATE OR REPLACE VIEW vw_locked_sap_users AS
SELECT
    user_sap_id,
    user_name,
    user_email,
    user_mobile,
    is_lock,
    modification_time as lock_time,
    modified_by as locked_by
FROM sap_info
WHERE delete_status = '0' AND is_lock = 'Y';

-- ============================================================
-- INSERT TEST DATA (OPTIONAL)
-- ============================================================

-- Insert test data for sap_info table (optional)
INSERT INTO sap_info (
    user_id, user_sap_id, user_name, user_email, user_mobile,
    user_mobile_country_code, user_level, sap_user_group, region,
    delete_status, creation_time
) VALUES (
    'TEST001', 'SAP001', 'John Doe', 'john.doe@example.com', '9876543210',
    '+91', 'LEVEL1', 'GROUP_A', 'NORTH',
    '0', CURRENT_TIMESTAMP
);

INSERT INTO sap_info (
    user_id, user_sap_id, user_name, user_email, user_mobile,
    user_mobile_country_code, user_level, sap_user_group, region,
    delete_status, creation_time
) VALUES (
    'TEST002', 'SAP002', 'Jane Smith', 'jane.smith@example.com', '9876543211',
    '+91', 'LEVEL2', 'GROUP_B', 'SOUTH',
    '0', CURRENT_TIMESTAMP
);